import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';

const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role;
create table kas_pick_data (id bigint generated always as identity primary key,report_date date,region text,hub text,wh_id text,mau_pu numeric,synced_at timestamptz default now());
create table kas_deli_data (like kas_pick_data including all);
create table kas_fd_data (like kas_pick_data including all);
create table kas_ca1_data (id bigint generated always as identity primary key,ngay date,lane text,tong_don numeric,synced_at timestamptz default now());`);
await db.exec(readFileSync('scripts/sql/ops-kpi-incremental-sync.sql','utf8'));
const ctx = vm.createContext({console,Date,Set,Number,JSON,Utilities:{formatDate:d=>d.toISOString().slice(0,10)}});
vm.runInContext(readFileSync('scripts/apps-script/ops-incremental-sync.gs','utf8'),ctx);
const liveLogs=[];
const liveCtx=vm.createContext({Date,Logger:{log:value=>liveLogs.push(value)}});
vm.runInContext(readFileSync('scripts/apps-script/ops-sync-live-20261009.gs','utf8'),liveCtx);
const md5 = s=>createHash('md5').update(s).digest('hex');
const manifest = async()=> (await db.query(`select ops_kpi_sync_manifest('pick') m`)).rows[0].m;
let checks=0;
const check=(ok)=>{assert.ok(ok); checks++;};
for (const value of ['', 'abc', 'Hub Việt Nam', '🚚', 'x'.repeat(55),'x'.repeat(56),'x'.repeat(64), 'x'.repeat(500)]) check(ctx.opsDeltaMd5_(value)===md5(value));
liveCtx.verifyOpsSyncRetry();
check(JSON.parse(liveLogs.at(-1)).retryChecksPassed===16);
check(liveCtx.opsDeltaMd5_('Hub Việt Nam')===md5('Hub Việt Nam'));
const sync=async(remote,rows)=>{
  const source=ctx.opsDeltaDayManifest_(remote.columns,rows,remote.date_column,ctx.opsDeltaMd5_);
  const changed=source.days.filter(d=>!remote.days.some(r=>r.day===d.day&&r.count===d.count&&r.hash===d.hash));
  const payload=changed.flatMap(d=>source.groups[d.day].rows);
  return (await db.query('select sync_ops_kpi_delta($1,$2,$3,$4) r',['pick',remote.token,JSON.stringify(source.days),JSON.stringify(payload)])).rows[0].r;
};
let remote=await manifest();
const row=(day,n,hub='Hub Việt Nam')=>remote.columns.map(c=>({report_date:day,region:'HCM',hub,wh_id:null,mau_pu:n})[c.name]);
let rows=[row('2026-10-07',3.5),row('2026-10-08',2),row('2026-10-08',2)];
let result=await sync(remote,rows); check(result.inserted===3);
let current=await manifest();
check(current.days[1].count===2);
result=await sync(remote,rows); check(result.unchanged&&result.inserted===0); // lost HTTP response retry
const ids=(await db.query('select id from kas_pick_data order by id')).rows.map(r=>r.id);
result=await sync(current,[...rows].reverse()); check(result.unchanged);
check(JSON.stringify(ids)===JSON.stringify((await db.query('select id from kas_pick_data order by id')).rows.map(r=>r.id)));
const stableIds=(await db.query("select id from kas_pick_data where report_date='2026-10-08' order by id")).rows.map(r=>r.id);
rows[0]=row('2026-10-07',4.5);
result=await sync(current,rows); check(result.inserted===1&&result.deleted===1);
const ids2=(await db.query("select id from kas_pick_data where report_date='2026-10-08' order by id")).rows.map(r=>r.id);
check(ids2.join(',')===stableIds.join(','));
current=await manifest();
const boundaryBefore=(await db.query('select synced_at::text as synced_at from kas_pick_data order by id desc limit 1')).rows[0].synced_at;
result=await sync(current,rows.slice(1)); check(result.deleted===1&&result.inserted===0);
check((await db.query('select synced_at::text as synced_at from kas_pick_data order by id desc limit 1')).rows[0].synced_at!==boundaryBefore);
current=await manifest();
result=await sync(current,rows.slice(1,2)); check(result.deleted===1&&result.inserted===0);
check((await manifest()).days[0].count===1);
current=await manifest();
await assert.rejects(()=>db.query('select sync_ops_kpi_delta($1,$2,$3,$4)',['pick',current.token,JSON.stringify([{day:'2026-10-08',count:2,hash:'0'.repeat(32)}]),'[]'])); checks++;
check((await manifest()).token===current.token);
await assert.rejects(()=>sync(remote,[row('2026-10-08',99)])); checks++;
await assert.rejects(()=>db.query("select ops_kpi_sync_manifest('leadtime')")); checks++;
check(ctx.opsDeltaNormalizeRows_(['report_date','region','hub','mau_pu'],[['2026-10-08','HCM','H',1]],remote.columns,'Asia/Ho_Chi_Minh')[0].includes(null));
assert.throws(()=>ctx.opsDeltaValidateWindow_('pick',[{day:'2026-10-07'}],'2026-10-09')); checks++;
ctx.opsDeltaValidateWindow_('fd',[{day:'2026-09-17'},{day:'2026-10-01'}],'2026-10-09'); checks++;
assert.throws(()=>ctx.opsDeltaNormalizeRows_(['report_date','region','hub','mau_pu'],[['2026-10-08','HCM','H','bad']],remote.columns,'Asia/Ho_Chi_Minh')); checks++;

check(ctx.opsDeltaNormalizeRows_(['report_date','region','hub','mau_pu'],[['2026-10-08 00:00:00','HCM','H',1]],remote.columns,'Asia/Ho_Chi_Minh')[0].includes('2026-10-08'));
console.log(JSON.stringify({checksPassed:checks,scope:'Postgres delta + Apps Script canonical hashing, duplicate multiplicity, retry, rollback, boundary, windows'}));
await db.close();
