-- Dev Admin access control for the GHN dashboard.
-- Apply this migration in Supabase before relying on the frontend gate.

create table if not exists public.access_logs (
  id bigint generated by default as identity primary key,
  email text not null,
  accessed_at timestamptz not null default now()
);

alter table public.access_logs enable row level security;

-- Remove any legacy policies on this table so an old permissive SELECT policy
-- cannot silently override the Dev Admin restriction below.
do $$
declare policy_name text;
begin
  for policy_name in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'access_logs'
  loop
    execute format('drop policy if exists %I on public.access_logs', policy_name);
  end loop;
end $$;

create policy "authenticated users can write their own access log"
  on public.access_logs
  for insert
  to authenticated
  with check (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

create policy "dev admin can read access logs"
  on public.access_logs
  for select
  to authenticated
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'vinhlt@ghn.vn');

grant insert, select on public.access_logs to authenticated;
