-- Migration: AI Chat Model & Reasoning Configuration (Scope All & User)
-- Source of truth for chatbot model/reasoning overrides per user or for all users.

-- 1. Table: Current Active Configurations
create table if not exists public.ai_chat_model_config (
  scope_type text not null check (scope_type in ('all', 'user')),
  scope_key text not null,
  user_id uuid,
  user_email text,
  model text not null,
  reasoning_effort text check (
    reasoning_effort is null or
    reasoning_effort in ('none', 'low', 'medium', 'high', 'xhigh', 'max')
  ),
  updated_by text not null,
  reason text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_chat_model_config_pk primary key (scope_type, scope_key),
  constraint ai_chat_model_config_scope_check check (
    (scope_type = 'all' and scope_key = 'all' and user_id is null and user_email is null) or
    (scope_type = 'user' and scope_key = user_id::text and user_id is not null and user_email is not null)
  ),
  constraint ai_chat_model_config_email_lowercase check (
    user_email is null or user_email = lower(user_email)
  )
);

-- 2. Table: Append-only Audit Trail
create table if not exists public.ai_chat_model_config_audit (
  id bigint generated by default as identity primary key,
  scope_type text not null check (scope_type in ('all', 'user')),
  scope_key text not null,
  user_id uuid,
  user_email text,
  previous_model text,
  previous_reasoning_effort text,
  new_model text,
  new_reasoning_effort text,
  action text not null check (action in ('set', 'reset')),
  changed_by text not null,
  reason text not null,
  created_at timestamptz not null default now()
);

-- 3. Indexes
create index if not exists idx_ai_chat_model_config_user_id on public.ai_chat_model_config (user_id);
create index if not exists idx_ai_chat_model_config_audit_created on public.ai_chat_model_config_audit (created_at desc);

-- 4. RLS & Least Privilege Grants
alter table public.ai_chat_model_config enable row level security;
alter table public.ai_chat_model_config_audit enable row level security;

revoke all on public.ai_chat_model_config from public, anon, authenticated;
revoke all on public.ai_chat_model_config_audit from public, anon, authenticated;
grant all on public.ai_chat_model_config to service_role;
grant all on public.ai_chat_model_config_audit to service_role;

-- 5. RPC: Search user by email for Model Config (Only returns userId and normalized email)
create or replace function public.admin_search_ai_chat_users(
  p_search text default null
) returns table (
  user_id uuid,
  email text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_term text := lower(trim(coalesce(p_search, '')));
  v_caller_role text := coalesce(
    nullif(current_setting('request.jwt.claim.role', true), ''),
    nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'role', ''),
    auth.role()
  );
  v_caller_email text := lower(trim(coalesce(
    nullif(current_setting('request.jwt.claim.email', true), ''),
    nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'email', ''),
    auth.jwt() ->> 'email',
    ''
  )));
  v_is_admin boolean := (
    v_caller_role = 'service_role'
    or v_caller_email = 'vinhlt@ghn.vn'
  );
begin
  if not v_is_admin then
    raise exception 'AI_CHAT_ADMIN_REQUIRED' using errcode = '42501';
  end if;

  if v_term = '' then
    return query
    select u.id as user_id, lower(u.email)::text as email
    from auth.users u
    where u.email is not null
    order by lower(u.email)
    limit 20;
  else
    return query
    select u.id as user_id, lower(u.email)::text as email
    from auth.users u
    where lower(u.email) like '%' || v_term || '%'
    order by lower(u.email)
    limit 20;
  end if;
end;
$$;

-- 6. RPC: Atomic Upsert & Audit Model Configuration
create or replace function public.admin_set_ai_chat_model_config(
  p_scope_type text,
  p_user_id uuid default null,
  p_user_email text default null,
  p_model text default null,
  p_reasoning_effort text default null,
  p_reason text default null,
  p_changed_by text default null
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_scope_type text := lower(trim(coalesce(p_scope_type, '')));
  v_scope_key text;
  v_target_user_id uuid := p_user_id;
  v_target_email text := lower(trim(coalesce(p_user_email, '')));
  v_model text := trim(coalesce(p_model, ''));
  v_reasoning text := nullif(trim(coalesce(p_reasoning_effort, '')), '');
  v_reason text := trim(coalesce(p_reason, ''));
  v_changed_by text := lower(trim(coalesce(p_changed_by, '')));
  v_audit_actor text;
  v_old public.ai_chat_model_config%rowtype;
  v_caller_role text := coalesce(
    nullif(current_setting('request.jwt.claim.role', true), ''),
    nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'role', ''),
    auth.role()
  );
  v_caller_email text := lower(trim(coalesce(
    nullif(current_setting('request.jwt.claim.email', true), ''),
    nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'email', ''),
    auth.jwt() ->> 'email',
    ''
  )));
  v_is_admin boolean := (
    v_caller_role = 'service_role'
    or v_caller_email = 'vinhlt@ghn.vn'
  );
begin
  if not v_is_admin or (v_changed_by <> '' and v_changed_by <> 'vinhlt@ghn.vn') then
    raise exception 'AI_CHAT_ADMIN_REQUIRED' using errcode = '42501';
  end if;

  if v_reason = '' then
    raise exception 'AI_CHAT_REASON_REQUIRED' using message = 'Lý do thay đổi cấu hình là bắt buộc.', errcode = '22023';
  end if;

  if v_model = '' then
    raise exception 'AI_CHAT_MODEL_REQUIRED' using message = 'Model không được để trống.', errcode = '22023';
  end if;

  if v_scope_type not in ('all', 'user') then
    raise exception 'AI_CHAT_INVALID_SCOPE' using message = 'Phạm vi cấu hình phải là "all" hoặc "user".', errcode = '22023';
  end if;

  if v_scope_type = 'all' then
    v_scope_key := 'all';
    v_target_user_id := null;
    v_target_email := null;
  else
    -- Resolve user
    if v_target_user_id is null and v_target_email <> '' then
      select id, lower(email) into v_target_user_id, v_target_email
      from auth.users
      where lower(email) = v_target_email
      limit 1;
    elsif v_target_user_id is not null then
      select lower(email) into v_target_email
      from auth.users
      where id = v_target_user_id
      limit 1;
    end if;

    if v_target_user_id is null or v_target_email is null or v_target_email = '' then
      raise exception 'AI_CHAT_USER_NOT_FOUND' using message = 'Không tìm thấy tài khoản người dùng hợp lệ.', errcode = 'P0002';
    end if;

    v_scope_key := v_target_user_id::text;
  end if;

  v_audit_actor := coalesce(nullif(v_changed_by, ''), 'service_role');

  -- Fetch previous config if exists
  select * into v_old
  from public.ai_chat_model_config
  where scope_type = v_scope_type and scope_key = v_scope_key;

  -- Upsert configuration
  insert into public.ai_chat_model_config (
    scope_type, scope_key, user_id, user_email, model, reasoning_effort, updated_by, reason, updated_at
  ) values (
    v_scope_type, v_scope_key, v_target_user_id, v_target_email, v_model, v_reasoning, v_audit_actor, v_reason, now()
  ) on conflict (scope_type, scope_key) do update set
    model = excluded.model,
    reasoning_effort = excluded.reasoning_effort,
    updated_by = excluded.updated_by,
    reason = excluded.reason,
    updated_at = now();

  -- Insert audit trail
  insert into public.ai_chat_model_config_audit (
    scope_type, scope_key, user_id, user_email,
    previous_model, previous_reasoning_effort,
    new_model, new_reasoning_effort,
    action, changed_by, reason
  ) values (
    v_scope_type, v_scope_key, v_target_user_id, v_target_email,
    v_old.model, v_old.reasoning_effort,
    v_model, v_reasoning,
    'set', v_audit_actor, v_reason
  );

  return jsonb_build_object(
    'success', true,
    'scopeType', v_scope_type,
    'scopeKey', v_scope_key,
    'userId', v_target_user_id,
    'userEmail', v_target_email,
    'model', v_model,
    'reasoningEffort', v_reasoning
  );
end;
$$;

-- 7. RPC: Atomic Reset & Audit Model Configuration
create or replace function public.admin_reset_ai_chat_model_config(
  p_scope_type text,
  p_user_id uuid default null,
  p_user_email text default null,
  p_reason text default null,
  p_changed_by text default null
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_scope_type text := lower(trim(coalesce(p_scope_type, '')));
  v_scope_key text;
  v_target_user_id uuid := p_user_id;
  v_target_email text := lower(trim(coalesce(p_user_email, '')));
  v_reason text := trim(coalesce(p_reason, ''));
  v_changed_by text := lower(trim(coalesce(p_changed_by, '')));
  v_audit_actor text;
  v_old public.ai_chat_model_config%rowtype;
  v_caller_role text := coalesce(
    nullif(current_setting('request.jwt.claim.role', true), ''),
    nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'role', ''),
    auth.role()
  );
  v_caller_email text := lower(trim(coalesce(
    nullif(current_setting('request.jwt.claim.email', true), ''),
    nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'email', ''),
    auth.jwt() ->> 'email',
    ''
  )));
  v_is_admin boolean := (
    v_caller_role = 'service_role'
    or v_caller_email = 'vinhlt@ghn.vn'
  );
begin
  if not v_is_admin or (v_changed_by <> '' and v_changed_by <> 'vinhlt@ghn.vn') then
    raise exception 'AI_CHAT_ADMIN_REQUIRED' using errcode = '42501';
  end if;

  if v_reason = '' then
    raise exception 'AI_CHAT_REASON_REQUIRED' using message = 'Lý do xóa cấu hình là bắt buộc.', errcode = '22023';
  end if;

  if v_scope_type not in ('all', 'user') then
    raise exception 'AI_CHAT_INVALID_SCOPE' using message = 'Phạm vi cấu hình phải là "all" hoặc "user".', errcode = '22023';
  end if;

  if v_scope_type = 'all' then
    v_scope_key := 'all';
    v_target_user_id := null;
    v_target_email := null;
  else
    if v_target_user_id is null and v_target_email <> '' then
      select id, lower(email) into v_target_user_id, v_target_email
      from auth.users
      where lower(email) = v_target_email
      limit 1;
    elsif v_target_user_id is not null then
      select lower(email) into v_target_email
      from auth.users
      where id = v_target_user_id
      limit 1;
    end if;

    if v_target_user_id is null then
      if v_target_email <> '' then
        select user_id into v_target_user_id
        from public.ai_chat_model_config
        where scope_type = 'user' and lower(user_email) = v_target_email
        limit 1;
      end if;
    end if;

    if v_target_user_id is null then
      raise exception 'AI_CHAT_USER_NOT_FOUND' using message = 'Không tìm thấy thông tin user để đặt lại cấu hình.', errcode = 'P0002';
    end if;

    v_scope_key := v_target_user_id::text;
  end if;

  v_audit_actor := coalesce(nullif(v_changed_by, ''), 'service_role');

  select * into v_old
  from public.ai_chat_model_config
  where scope_type = v_scope_type and scope_key = v_scope_key;

  if not found then
    insert into public.ai_chat_model_config_audit (
      scope_type, scope_key, user_id, user_email,
      previous_model, previous_reasoning_effort,
      new_model, new_reasoning_effort,
      action, changed_by, reason
    ) values (
      v_scope_type, v_scope_key, v_target_user_id, coalesce(v_target_email, v_old.user_email),
      null, null, null, null,
      'reset', v_audit_actor, v_reason
    );
    return jsonb_build_object('success', true, 'message', 'Cấu hình đã ở mặc định.');
  end if;

  delete from public.ai_chat_model_config
  where scope_type = v_scope_type and scope_key = v_scope_key;

  insert into public.ai_chat_model_config_audit (
    scope_type, scope_key, user_id, user_email,
    previous_model, previous_reasoning_effort,
    new_model, new_reasoning_effort,
    action, changed_by, reason
  ) values (
    v_scope_type, v_scope_key, v_target_user_id, coalesce(v_target_email, v_old.user_email),
    v_old.model, v_old.reasoning_effort,
    null, null,
    'reset', v_audit_actor, v_reason
  );

  return jsonb_build_object('success', true, 'scopeType', v_scope_type, 'scopeKey', v_scope_key);
end;
$$;

-- 8. Function Privileges
-- Strictly revoke execute from public, anon, and authenticated with full signatures
revoke execute on function public.admin_search_ai_chat_users(text) from public, anon, authenticated;
revoke execute on function public.admin_set_ai_chat_model_config(text, uuid, text, text, text, text, text) from public, anon, authenticated;
revoke execute on function public.admin_reset_ai_chat_model_config(text, uuid, text, text, text) from public, anon, authenticated;

-- Grant execution strictly to service_role only
grant execute on function public.admin_search_ai_chat_users(text) to service_role;
grant execute on function public.admin_set_ai_chat_model_config(text, uuid, text, text, text, text, text) to service_role;
grant execute on function public.admin_reset_ai_chat_model_config(text, uuid, text, text, text) to service_role;
