-- Migration: AI Operations, Quota Overrides, and Question Research Layer
-- Applies quota overrides, audit logging, research telemetry, retention purging, and dev-admin RPCs.

-- 1. Table: User Quota Overrides
create table if not exists public.ai_chat_user_quota (
  user_id uuid primary key,
  user_email text not null,
  daily_turn_limit integer check (daily_turn_limit is null or daily_turn_limit >= 0),
  is_unlimited boolean not null default false,
  updated_by text not null,
  reason text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_chat_user_quota_limit_check check (
    (is_unlimited = true and daily_turn_limit is null) or
    (is_unlimited = false and daily_turn_limit is not null)
  )
);

-- 2. Table: Quota Audit Log
create table if not exists public.ai_chat_quota_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  user_email text,
  previous_limit integer,
  previous_is_unlimited boolean default false,
  new_limit integer,
  new_is_unlimited boolean default false,
  action text not null check (action in ('set_override', 'reset_default')),
  changed_by text not null,
  reason text not null,
  created_at timestamptz not null default now()
);

-- 3. Alter Table: ai_chat_requests to include research & error details
alter table public.ai_chat_requests
  add column if not exists user_email text,
  add column if not exists question text,
  add column if not exists question_normalized text,
  add column if not exists question_fingerprint text,
  add column if not exists client_filter text,
  add column if not exists active_tab text,
  add column if not exists model text,
  add column if not exists total_tokens integer default 0,
  add column if not exists input_tokens integer default 0,
  add column if not exists output_tokens integer default 0,
  add column if not exists reasoning_tokens integer default 0,
  add column if not exists cached_input_tokens integer default 0,
  add column if not exists latency_ms integer default 0,
  add column if not exists error_code text,
  add column if not exists error_message text;

alter table public.ai_chat_requests drop constraint if exists ai_chat_requests_status_check;
alter table public.ai_chat_requests add constraint ai_chat_requests_status_check
  check (status in ('in_flight', 'completed', 'failed', 'aborted', 'rejected_by_quota'));

-- 4. Indexes for operations and analytics
create index if not exists idx_ai_chat_requests_started_at on public.ai_chat_requests (started_at desc);
create index if not exists idx_ai_chat_requests_quota_date_status on public.ai_chat_requests (quota_date, status);
create index if not exists idx_ai_chat_requests_user_date on public.ai_chat_requests (user_id, quota_date);
create index if not exists idx_ai_chat_requests_email on public.ai_chat_requests (lower(user_email));
create index if not exists idx_ai_chat_requests_fingerprint on public.ai_chat_requests (question_fingerprint);
create index if not exists idx_ai_chat_quota_audit_created on public.ai_chat_quota_audit (created_at desc);
create index if not exists idx_ai_chat_user_quota_email on public.ai_chat_user_quota (lower(user_email));

-- 5. RLS Setup
alter table public.ai_chat_user_quota enable row level security;
alter table public.ai_chat_quota_audit enable row level security;

revoke all on public.ai_chat_user_quota from anon, authenticated;
revoke all on public.ai_chat_quota_audit from anon, authenticated;
grant all on public.ai_chat_user_quota to service_role;
grant all on public.ai_chat_quota_audit to service_role;

-- Drop legacy policies if any
do $$
declare pol record;
begin
  for pol in select policyname, tablename from pg_policies where schemaname = 'public' and tablename in ('ai_chat_user_quota', 'ai_chat_quota_audit', 'ai_chat_requests', 'ai_chat_usage', 'ai_chat_quota_daily') loop
    execute format('drop policy if exists %I on public.%I', pol.policyname, pol.tablename);
  end loop;
end $$;

-- Dev Admin Read Policies (Fail-closed: only vinhlt@ghn.vn)
create policy "dev admin can read ai_chat_user_quota"
  on public.ai_chat_user_quota for select to authenticated
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'vinhlt@ghn.vn');

create policy "dev admin can read ai_chat_quota_audit"
  on public.ai_chat_quota_audit for select to authenticated
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'vinhlt@ghn.vn');

create policy "dev admin can read ai_chat_requests"
  on public.ai_chat_requests for select to authenticated
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'vinhlt@ghn.vn');

create policy "dev admin can read ai_chat_usage"
  on public.ai_chat_usage for select to authenticated
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'vinhlt@ghn.vn');

create policy "dev admin can read ai_chat_quota_daily"
  on public.ai_chat_quota_daily for select to authenticated
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'vinhlt@ghn.vn');

-- Authenticated users can read their own quota override if one exists
create policy "users can read own quota override"
  on public.ai_chat_user_quota for select to authenticated
  using (auth.uid() = user_id);

grant select on public.ai_chat_user_quota to authenticated;
grant select on public.ai_chat_quota_audit to authenticated;
grant select on public.ai_chat_requests to authenticated;
grant select on public.ai_chat_usage to authenticated;
grant select on public.ai_chat_quota_daily to authenticated;

-- 6. RPC: reserve_ai_chat_request (Enhanced with Overrides & Research Data)
create or replace function public.reserve_ai_chat_request(
  p_user_id uuid,
  p_org_id text,
  p_request_id uuid,
  p_payload_hash text,
  p_reserved_microusd bigint,
  p_user_turn_limit integer,
  p_org_turn_limit integer,
  p_user_budget_microusd bigint,
  p_org_budget_microusd bigint,
  p_user_email text default null,
  p_question text default null,
  p_question_normalized text default null,
  p_question_fingerprint text default null,
  p_client_filter text default null,
  p_active_tab text default null,
  p_model text default null
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_day date := (now() at time zone 'Asia/Ho_Chi_Minh')::date;
  v_existing public.ai_chat_requests%rowtype;
  v_org public.ai_chat_quota_daily%rowtype;
  v_user public.ai_chat_quota_daily%rowtype;
  v_override public.ai_chat_user_quota%rowtype;
  v_effective_user_turn_limit integer := p_user_turn_limit;
  v_is_unlimited boolean := false;
begin
  if coalesce(auth.jwt() ->> 'role', '') <> 'service_role' then
    raise exception 'AI_CHAT_SERVICE_ROLE_REQUIRED' using errcode = '42501';
  end if;
  if p_reserved_microusd <= 0 or p_user_turn_limit <= 0 or p_org_turn_limit <= 0 then
    raise exception 'AI_CHAT_INVALID_LIMITS' using errcode = '22023';
  end if;

  -- Check user quota override
  select * into v_override
  from public.ai_chat_user_quota
  where user_id = p_user_id;

  if found then
    if v_override.is_unlimited then
      v_is_unlimited := true;
      v_effective_user_turn_limit := 2147483647;
    else
      v_effective_user_turn_limit := v_override.daily_turn_limit;
    end if;
  end if;

  insert into public.ai_chat_requests (
    request_id, user_id, org_id, payload_hash, status, reserved_microusd, quota_date,
    user_email, question, question_normalized, question_fingerprint,
    client_filter, active_tab, model, started_at
  ) values (
    p_request_id, p_user_id, p_org_id, p_payload_hash, 'in_flight', p_reserved_microusd, v_day,
    p_user_email, p_question, p_question_normalized, p_question_fingerprint,
    p_client_filter, p_active_tab, p_model, now()
  ) on conflict (request_id) do nothing;

  if not found then
    select * into v_existing
    from public.ai_chat_requests
    where request_id = p_request_id
    for update;
    if v_existing.payload_hash <> p_payload_hash or v_existing.user_id <> p_user_id then
      raise exception 'AI_CHAT_PAYLOAD_CONFLICT' using errcode = 'P0001';
    end if;
    raise exception 'AI_CHAT_DUPLICATE' using errcode = 'P0001';
  end if;

  insert into public.ai_chat_quota_daily (scope_type, scope_id, usage_date)
  values ('org', p_org_id, v_day), ('user', p_user_id::text, v_day)
  on conflict do nothing;

  -- Lock in deterministic org -> user order to prevent deadlocks
  select * into v_org from public.ai_chat_quota_daily
  where scope_type = 'org' and scope_id = p_org_id and usage_date = v_day
  for update;
  select * into v_user from public.ai_chat_quota_daily
  where scope_type = 'user' and scope_id = p_user_id::text and usage_date = v_day
  for update;

  if v_org.turn_count >= p_org_turn_limit or (not v_is_unlimited and v_user.turn_count >= v_effective_user_turn_limit) then
    raise exception 'AI_CHAT_TURN_LIMIT' using errcode = 'P0001';
  end if;

  if v_org.used_microusd + v_org.reserved_microusd + p_reserved_microusd > p_org_budget_microusd
     or (not v_is_unlimited and v_user.used_microusd + v_user.reserved_microusd + p_reserved_microusd > p_user_budget_microusd) then
    raise exception 'AI_CHAT_BUDGET_LIMIT' using errcode = 'P0001';
  end if;

  update public.ai_chat_quota_daily
  set turn_count = turn_count + 1,
      reserved_microusd = reserved_microusd + p_reserved_microusd,
      updated_at = now()
  where usage_date = v_day
    and ((scope_type = 'org' and scope_id = p_org_id)
      or (scope_type = 'user' and scope_id = p_user_id::text));

  return jsonb_build_object(
    'requestId', p_request_id,
    'quotaDate', v_day,
    'reservedMicrousd', p_reserved_microusd,
    'usedToday', v_user.turn_count + 1,
    'dailyLimit', case when v_is_unlimited then null else v_effective_user_turn_limit end,
    'isUnlimited', v_is_unlimited,
    'remainingTurns', case when v_is_unlimited then null else greatest(0, v_effective_user_turn_limit - (v_user.turn_count + 1)) end,
    'resetAt', ((v_day + 1)::timestamp at time zone 'Asia/Ho_Chi_Minh')
  );
end;
$$;

-- 7. RPC: finalize_ai_chat_request (Enhanced with Refund & Token Breakdown)
create or replace function public.finalize_ai_chat_request(
  p_request_id uuid,
  p_status text,
  p_actual_microusd bigint,
  p_usage jsonb,
  p_tool_names text[],
  p_refund_turn boolean default false,
  p_error_code text default null,
  p_error_message text default null
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_request public.ai_chat_requests%rowtype;
  v_item jsonb;
  v_total_tokens integer := 0;
  v_input_tokens integer := 0;
  v_output_tokens integer := 0;
  v_reasoning_tokens integer := 0;
  v_cached_input_tokens integer := 0;
  v_total_latency integer := 0;
begin
  if coalesce(auth.jwt() ->> 'role', '') <> 'service_role' then
    raise exception 'AI_CHAT_SERVICE_ROLE_REQUIRED' using errcode = '42501';
  end if;
  if p_status not in ('completed', 'failed', 'aborted') or p_actual_microusd < 0 then
    raise exception 'AI_CHAT_INVALID_FINAL_STATE' using errcode = '22023';
  end if;

  select * into v_request from public.ai_chat_requests
  where request_id = p_request_id
  for update;
  if not found then raise exception 'AI_CHAT_REQUEST_NOT_FOUND' using errcode = 'P0001'; end if;
  if v_request.status not in ('in_flight') then return false; end if;

  -- Reconcile daily quota ledger. If p_refund_turn is true, decrement turn_count.
  update public.ai_chat_quota_daily
  set reserved_microusd = greatest(0, reserved_microusd - v_request.reserved_microusd),
      used_microusd = used_microusd + p_actual_microusd,
      turn_count = case when p_refund_turn then greatest(0, turn_count - 1) else turn_count end,
      updated_at = now()
  where usage_date = v_request.quota_date
    and ((scope_type = 'org' and scope_id = v_request.org_id)
      or (scope_type = 'user' and scope_id = v_request.user_id::text));

  -- Tally usage items
  for v_item in select value from jsonb_array_elements(coalesce(p_usage, '[]'::jsonb)) loop
    v_input_tokens := v_input_tokens + coalesce((v_item ->> 'inputTokens')::integer, 0);
    v_cached_input_tokens := v_cached_input_tokens + coalesce((v_item ->> 'cachedInputTokens')::integer, 0);
    v_output_tokens := v_output_tokens + coalesce((v_item ->> 'outputTokens')::integer, 0);
    v_reasoning_tokens := v_reasoning_tokens + coalesce((v_item ->> 'reasoningTokens')::integer, 0);
    v_total_latency := v_total_latency + coalesce((v_item ->> 'latencyMs')::integer, 0);

    insert into public.ai_chat_usage (
      request_id, round, model, effort, input_tokens, cached_input_tokens,
      output_tokens, reasoning_tokens, estimated_microusd, tool_names, latency_ms, status
    ) values (
      p_request_id,
      (v_item ->> 'round')::integer,
      coalesce(v_item ->> 'model', 'unknown'),
      coalesce(v_item ->> 'effort', 'unknown'),
      coalesce((v_item ->> 'inputTokens')::integer, 0),
      coalesce((v_item ->> 'cachedInputTokens')::integer, 0),
      coalesce((v_item ->> 'outputTokens')::integer, 0),
      coalesce((v_item ->> 'reasoningTokens')::integer, 0),
      coalesce((v_item ->> 'estimatedMicrousd')::bigint, 0),
      coalesce(array(select jsonb_array_elements_text(coalesce(v_item -> 'toolNames', '[]'::jsonb))), '{}'),
      coalesce((v_item ->> 'latencyMs')::integer, 0),
      coalesce(v_item ->> 'status', p_status)
    ) on conflict (request_id, round) do nothing;
  end loop;

  v_total_tokens := v_input_tokens + v_output_tokens;

  update public.ai_chat_requests
  set status = p_status,
      actual_microusd = p_actual_microusd,
      tool_names = coalesce(p_tool_names, '{}'),
      total_tokens = v_total_tokens,
      input_tokens = v_input_tokens,
      output_tokens = v_output_tokens,
      reasoning_tokens = v_reasoning_tokens,
      cached_input_tokens = v_cached_input_tokens,
      latency_ms = v_total_latency,
      error_code = p_error_code,
      error_message = p_error_message,
      finished_at = now()
  where request_id = p_request_id;

  return true;
end;
$$;

-- 8. RPC: record_ai_chat_quota_rejection
create or replace function public.record_ai_chat_quota_rejection(
  p_user_id uuid,
  p_org_id text,
  p_request_id uuid,
  p_payload_hash text,
  p_user_email text default null,
  p_question text default null,
  p_question_normalized text default null,
  p_question_fingerprint text default null,
  p_client_filter text default null,
  p_active_tab text default null,
  p_model text default null
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_day date := (now() at time zone 'Asia/Ho_Chi_Minh')::date;
begin
  if coalesce(auth.jwt() ->> 'role', '') <> 'service_role' then
    raise exception 'AI_CHAT_SERVICE_ROLE_REQUIRED' using errcode = '42501';
  end if;

  insert into public.ai_chat_requests (
    request_id, user_id, org_id, payload_hash, status, reserved_microusd, actual_microusd,
    quota_date, user_email, question, question_normalized, question_fingerprint,
    client_filter, active_tab, model, error_code, error_message, started_at, finished_at
  ) values (
    p_request_id, p_user_id, p_org_id, p_payload_hash, 'rejected_by_quota', 0, 0,
    v_day, p_user_email, p_question, p_question_normalized, p_question_fingerprint,
    p_client_filter, p_active_tab, p_model, 'CHAT_QUOTA_EXCEEDED', 'Hôm nay bạn đã hết lượt hoặc ngân sách chatbot.', now(), now()
  ) on conflict (request_id) do nothing;

  return true;
end;
$$;

-- 9. RPC: get_user_ai_chat_quota (Query quota status for user or dev admin)
create or replace function public.get_user_ai_chat_quota(p_user_id uuid default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_target_user uuid := coalesce(p_user_id, auth.uid());
  v_day date := (now() at time zone 'Asia/Ho_Chi_Minh')::date;
  v_override public.ai_chat_user_quota%rowtype;
  v_used integer := 0;
  v_daily_limit integer := 10;
  v_is_unlimited boolean := false;
  v_has_override boolean := false;
  v_caller_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  v_is_admin boolean := (v_caller_email = 'vinhlt@ghn.vn' or coalesce(auth.jwt() ->> 'role', '') = 'service_role');
begin
  if v_target_user is null then
    raise exception 'AI_CHAT_USER_REQUIRED' using errcode = '42501';
  end if;
  if v_target_user <> auth.uid() and not v_is_admin then
    raise exception 'AI_CHAT_FORBIDDEN' using errcode = '42501';
  end if;

  -- Check override
  select * into v_override from public.ai_chat_user_quota where user_id = v_target_user;
  if found then
    v_has_override := true;
    if v_override.is_unlimited then
      v_is_unlimited := true;
      v_daily_limit := null;
    else
      v_daily_limit := v_override.daily_turn_limit;
    end if;
  end if;

  -- Check usage today
  select turn_count into v_used from public.ai_chat_quota_daily
  where scope_type = 'user' and scope_id = v_target_user::text and usage_date = v_day;
  v_used := coalesce(v_used, 0);

  return jsonb_build_object(
    'userId', v_target_user,
    'quotaDate', v_day,
    'dailyLimit', v_daily_limit,
    'usedToday', v_used,
    'isUnlimited', v_is_unlimited,
    'hasOverride', v_has_override,
    'remainingTurns', case when v_is_unlimited then null else greatest(0, v_daily_limit - v_used) end,
    'resetAt', ((v_day + 1)::timestamp at time zone 'Asia/Ho_Chi_Minh')
  );
end;
$$;

-- 10. RPC: admin_set_user_quota_override
create or replace function public.admin_set_user_quota_override(
  p_user_id uuid,
  p_user_email text,
  p_daily_turn_limit integer,
  p_is_unlimited boolean,
  p_reason text,
  p_changed_by text default null
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_caller_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  v_changed_by text := coalesce(nullif(lower(trim(p_changed_by)), ''), nullif(v_caller_email, ''), 'service_role');
  v_is_admin boolean := (v_caller_email = 'vinhlt@ghn.vn' or coalesce(auth.jwt() ->> 'role', '') = 'service_role');
  v_old public.ai_chat_user_quota%rowtype;
begin
  if not v_is_admin then
    raise exception 'AI_CHAT_ADMIN_REQUIRED' using errcode = '42501';
  end if;
  if p_reason is null or trim(p_reason) = '' then
    raise exception 'AI_CHAT_REASON_REQUIRED' using errcode = '22023';
  end if;
  if not p_is_unlimited and (p_daily_turn_limit is null or p_daily_turn_limit < 0) then
    raise exception 'AI_CHAT_INVALID_LIMIT' using errcode = '22023';
  end if;

  select * into v_old from public.ai_chat_user_quota where user_id = p_user_id;

  insert into public.ai_chat_user_quota (
    user_id, user_email, daily_turn_limit, is_unlimited, updated_by, reason, updated_at
  ) values (
    p_user_id, lower(p_user_email), case when p_is_unlimited then null else p_daily_turn_limit end,
    p_is_unlimited, v_changed_by, trim(p_reason), now()
  ) on conflict (user_id) do update set
    daily_turn_limit = excluded.daily_turn_limit,
    is_unlimited = excluded.is_unlimited,
    updated_by = excluded.updated_by,
    reason = excluded.reason,
    updated_at = now();

  insert into public.ai_chat_quota_audit (
    user_id, user_email, previous_limit, previous_is_unlimited,
    new_limit, new_is_unlimited, action, changed_by, reason
  ) values (
    p_user_id, lower(p_user_email), v_old.daily_turn_limit, coalesce(v_old.is_unlimited, false),
    case when p_is_unlimited then null else p_daily_turn_limit end, p_is_unlimited,
    'set_override', v_changed_by, trim(p_reason)
  );

  return jsonb_build_object('success', true, 'userId', p_user_id, 'isUnlimited', p_is_unlimited, 'limit', p_daily_turn_limit);
end;
$$;

-- 11. RPC: admin_reset_user_quota
create or replace function public.admin_reset_user_quota(
  p_user_id uuid,
  p_reason text,
  p_changed_by text default null
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_caller_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  v_changed_by text := coalesce(nullif(lower(trim(p_changed_by)), ''), nullif(v_caller_email, ''), 'service_role');
  v_is_admin boolean := (v_caller_email = 'vinhlt@ghn.vn' or coalesce(auth.jwt() ->> 'role', '') = 'service_role');
  v_old public.ai_chat_user_quota%rowtype;
begin
  if not v_is_admin then
    raise exception 'AI_CHAT_ADMIN_REQUIRED' using errcode = '42501';
  end if;
  if p_reason is null or trim(p_reason) = '' then
    raise exception 'AI_CHAT_REASON_REQUIRED' using errcode = '22023';
  end if;

  select * into v_old from public.ai_chat_user_quota where user_id = p_user_id;
  if not found then
    return jsonb_build_object('success', true, 'message', 'User already on default quota');
  end if;

  delete from public.ai_chat_user_quota where user_id = p_user_id;

  insert into public.ai_chat_quota_audit (
    user_id, user_email, previous_limit, previous_is_unlimited,
    new_limit, new_is_unlimited, action, changed_by, reason
  ) values (
    p_user_id, v_old.user_email, v_old.daily_turn_limit, v_old.is_unlimited,
    10, false, 'reset_default', v_changed_by, trim(p_reason)
  );

  return jsonb_build_object('success', true, 'userId', p_user_id, 'defaultLimit', 10);
end;
$$;

-- 12. RPC: purge_old_ai_chat_questions (Retention Policy - default 90 days)
create or replace function public.purge_old_ai_chat_questions(
  p_retention_days integer default 90
) returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_caller_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  v_is_admin boolean := (v_caller_email = 'vinhlt@ghn.vn' or coalesce(auth.jwt() ->> 'role', '') = 'service_role');
  v_cutoff timestamptz;
  v_purged integer := 0;
begin
  if not v_is_admin then
    raise exception 'AI_CHAT_ADMIN_REQUIRED' using errcode = '42501';
  end if;
  if p_retention_days < 1 then
    raise exception 'AI_CHAT_INVALID_RETENTION' using errcode = '22023';
  end if;

  v_cutoff := now() - (p_retention_days || ' days')::interval;

  update public.ai_chat_requests
  set question = '[PURGED_BY_RETENTION]',
      question_normalized = '[PURGED]'
  where started_at < v_cutoff
    and question is not null
    and question <> '[PURGED_BY_RETENTION]';

  get diagnostics v_purged = row_count;
  return v_purged;
end;
$$;

-- Revoke execute from public / anon
revoke all on function public.reserve_ai_chat_request from public, anon, authenticated;
revoke all on function public.finalize_ai_chat_request from public, anon, authenticated;
revoke all on function public.record_ai_chat_quota_rejection from public, anon, authenticated;
revoke all on function public.get_user_ai_chat_quota from public, anon;
revoke all on function public.admin_set_user_quota_override from public, anon;
revoke all on function public.admin_reset_user_quota from public, anon;
revoke all on function public.purge_old_ai_chat_questions from public, anon;

-- Grant execution to proper roles
grant execute on function public.reserve_ai_chat_request to service_role;
grant execute on function public.finalize_ai_chat_request to service_role;
grant execute on function public.record_ai_chat_quota_rejection to service_role;
grant execute on function public.get_user_ai_chat_quota to authenticated, service_role;
grant execute on function public.admin_set_user_quota_override to authenticated, service_role;
grant execute on function public.admin_reset_user_quota to authenticated, service_role;
grant execute on function public.purge_old_ai_chat_questions to authenticated, service_role;
